### ISSUE TITLE
Add Catppuccin themes

### ISSUE THREAD

**Issue by RazorSiM** [antfu/textmate-grammars-themes#2]
### Clear and concise description of the problem

It would be cool to have Catppuccin support from: https://github.com/catppuccin/vscode/tree/compiled

### Suggested solution

Source is here: https://github.com/catppuccin/vscode/tree/compiled

I'm already using those with Shikiji, so I suppose it's going to work properly by just adding the json source in `source-themes.ts`.

I'm following the contribution guide to open a PR :) 

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by antfu** [comment]
Happy to have them, PR welcome :)
